name: Build Python Package

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow
  pull_request:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: python-package
          path: dist/
